KK_FILE_PATH = r"C:\dev\data\josh-fyp\inputs\national_mapping_data_josh\Disease\KK_3_7_14_anon.xlsx"
GAM_FILE_PATH = r"C:\dev\data\josh-fyp\inputs\national_mapping_data_josh\Disease\Gambella_3_7_14_anon.xlsx"
IND_FILE_PATH = r"C:\dev\data\josh-fyp\inputs\national_mapping_data_josh\Disease\Individual_3_7_14_anon.xlsx"
SCH_FILE_PATH = r"C:\dev\data\josh-fyp\inputs\national_mapping_data_josh\Disease\Schools_3_7_14_anon.xlsx"
SHA_FILE_PATH = r"C:\dev\data\josh-fyp\inputs\national_mapping_data_josh\Disease\Shaematobium_3_7_14_anon.xlsx"
WSH_FILE_PATH = r"C:\dev\data\josh-fyp\inputs\national_mapping_data_josh\WASH-cleaned\WASHData.xlsx"
ELE_FILE_PATH = r"C:\dev\data\josh-fyp\inputs\national_mapping_data_josh\elevation\elevations.csv"
