name: josh-fyp
dependencies:
    - python==3.7.4
    - pandas==1.0.0
    - matplotlib==3.1.3
    - xlrd==1.2.0
    - requests==2.22.0
    - scipy==1.4.1
    - pip==19.3.1
    - pip:
          - sklearn==0.0
