name: josh-fyp
dependencies:
    - python==3.7.4
    - pandas==1.0.0
    - matplotlib==3.1.3
    - xlrd==1.2.0
    - requests==2.22.0
    - scipy==1.4.1
    - pip==19.3.1
    - geos=3.7.1
    - geopandas=0.6.1
    - geoplot=0.4.0       # conda install geoplot -c conda-forge
    - pip:
          - sklearn==0.0
          - regex==2020.2.20
          - spacy==2.2.3
          # python -m spacy download en
          - nltk==3.4.5
          - pip install virtualenv # appdirs-1.4.3 distlib-0.3.0 filelock-3.0.12 virtualenv-20.0.18
          - wordcloud-1.6.0
          - cftime-1.1.3
          - latlon-utils-0.0.5
          - netCDF4-1.5.3
          - # google-cloud-language
